### ISSUE TITLE
'GL2Webcam.h' file not found

### ISSUE THREAD

**Issue by RomainAl** [daitomanabe/ofxGL2Webcam#4]
Hi ! Thx a lot for this awesome addon !
I'm pretty new in openframeworks/xcode but I begin to know its more and more...

I do everything that you say in your read me, but I still have this error log :
'GL2Webcam.h' file not found

When I try your xcode example, it works well, but not, when I'm trying to make mine (but the same) with project generator !?

Have you an idea, to help me ?
Thx in advance

PS : I use macOS Catalina 10.15.7 (MacBook Pro 2019, 16 inchs)

<img width="1847" alt="Capture d’écran 2021-02-12 à 10 17 31" src="https://user-images.githubusercontent.com/60849348/107750331-2d36a580-6d1c-11eb-8d13-def36a656781.png">
<img width="1847" alt="Capture d’écran 2021-02-12 à 10 17 42" src="https://user-images.githubusercontent.com/60849348/107750343-3162c300-6d1c-11eb-933b-7677a107032d.png">
<img width="1847" alt="Capture d’écran 2021-02-12 à 10 17 49" src="https://user-images.githubusercontent.com/60849348/107750346-31fb5980-6d1c-11eb-8367-58a4cc0c9cbf.png">

**Comment by 2bbb** [comment]
@RomainAl  please use latest master.

**Comment by RomainAl** [comment]
Yes, it works now ! Thx
